USE [master]
GO

CREATE SERVER AUDIT [SQL_Hardening_Audit]
TO APPLICATION_LOG
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
	,AUDIT_GUID = '38691227-3c88-4036-87ee-d1745cd0b394'
)
WHERE ([server_principal_name]<>'NTSERVICE\SQLSERVERAGENT' AND [server_principal_name]<>'NT AUTHORITY\SERVICE')
ALTER SERVER AUDIT [SQL_Hardening_Audit] WITH (STATE = ON)
GO
