ALTER INDEX IX_ACTION_COLUMNS_ACTION_ID_DB_COLUMN ON ACTION_COLUMNS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX Adiwork_DUID ON adi_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_ADI_WORK_MRN_FAC ON adi_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_ADI_WORK_imnet ON adi_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX PK_AGENT_PARMS ON AGENT_PARMS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX PK_ansi_RemarkCodes ON ansi_RemarkCodes REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX i_atemp_PhysDefRpt ON atemp_trans_PhysDefRpt REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_AUTHENTICATORS_ASSIGNED_ID ON authenticators REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_AUTHENTICATORS_PS_JOB_ID ON authenticators REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_AUTHENTICATORS_USERINSTANCEID ON authenticators REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_AUTHENTICATORS_VERSION_ID ON authenticators REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX PK_authenticators ON authenticators REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX CDI_DATE ON CAB_DEL_ITEMS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX CDI_DATE ON CAB_DEL_ITEMS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX CDI_IMNET_ID ON CAB_DEL_ITEMS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_CABINET_XREF_STATECHANGEDBY_TEXTEDITINGSTATE ON CABINET_XREF REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX PK_CABINET_XREF ON CABINET_XREF REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX CW_USER ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_Composite_Work_Enc_Fac ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_COMPOSITE_WORK_ENCOUNTER_MRN_FACILITY ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_COMPOSITE_WORK_MRN_ENCOUNTER_FACILITY ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_Composite_Work_Mrn_Fac ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_DICTATION_JOB_DOCTYPE_ID ON DICTATION_JOB REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_DICTATION_JOB_ENCOUNTER_FACILITY ON DICTATION_JOB REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX PK_DICTATION_JOB ON DICTATION_JOB REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX D_ORD ON DOCUMENT_NAMES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX D_TAG_SETID ON DOCUMENT_NAMES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX DN_DOCTYPEID ON DOCUMENT_NAMES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_DOCUMENT_NAMES_CALCTABLE_ID ON DOCUMENT_NAMES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX docsta_date ON DOCUMENT_STATISTICS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX docsta_doctype ON DOCUMENT_STATISTICS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX docsta_facility ON DOCUMENT_STATISTICS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX docsta_template ON DOCUMENT_STATISTICS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX EL_WHEN ON ERROR_LOG REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX follow_up_duid ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX FOLLOW_UP_IX_AGINGDATE ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX follow_up_QUESTATUS ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX follow_up_STATUS ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX fu_checkoutby ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX fu_id ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_FOLLOW_UP_FOLDER_FACILITY ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_FOLLOW_UP_QUEUE_DEF_TYPE ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_FollowUp_Type_StatusId ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_PURGEROLLBACK_ARCHIVEDIMNET ON MARK_FOR_PURGE_ROLLBACK REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_PURGEROLLBACK_ENCOUNTER_Facility ON MARK_FOR_PURGE_ROLLBACK REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_PURGEROLLBACK_PREIMNET ON MARK_FOR_PURGE_ROLLBACK REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX PK_Output_ListOfValue_seq ON Output_ListOfValue REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = OFF) 

ALTER INDEX IX_PAYOR_FILE_SET_ID_PAYOR_CODE ON PAYOR_FILE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX P_CODE ON PAYOR_FILE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_PRINT_ACCESS_ID ON Print_Access REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_PRINT_ACCESS_UserID ON Print_Access REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX PD_WHEN ON PRODUCTIVITY REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX PK_qualifiers ON QUALIFIERS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX RV_DESC ON RECORD_VIEWS_DOMAIN REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX RV_DOCUMENT ON RECORD_VIEWS_DOMAIN REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX RV_VT_DESC_DOC ON RECORD_VIEWS_DOMAIN REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX pk_segments ON SEGMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_SERVICE_FILE_SERVICE_NAME ON SERVICE_FILE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_SIGN_CONTROL_SIGN ON SIGN_CONTROL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_SIGNATURES_FOLDER_FACILITY ON SIGNATURES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_SIGNATURES_NAME ON SIGNATURES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX SIG_ID ON SIGNATURES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX SIG_IMNET ON SIGNATURES REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_SQL_FRAGMENTS_StoredProc_Name ON SQL_FRAGMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_SQL_FRAGMENTS_TYPE ON SQL_FRAGMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX SF_KEY ON SQL_FRAGMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_SQLCRITERIA_RptGuid ON SQLCriteria REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = OFF) 

ALTER INDEX PK_SYSPARMS_GLOBAL ON SYSPARMS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = OFF) 
ALTER INDEX UNC_SYSPARMS_GlobalParentID_GlobalName ON SYSPARMS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IDX_SYSSTATS_GLOBAL_GlobalId ON SYSSTATS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IDX_SYSSTATS_GLOBAL_ParentId ON SYSSTATS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX pk_trans_actions ON trans_actions REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
--
ALTER INDEX pk_trans_list ON TRANS_LIST REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX pk_trans_segments ON TRANS_SEGMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX pk_trans_table_actions ON trans_table_actions REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX pk_transactions ON TRANSACTIONS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_USER_FACILITY_PHYSICIAN_CODE_FACILITY ON User_Facility REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IXC_USER_FACILITY_USER_ID_FACILITY ON User_Facility REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX USERFAC_FACID ON User_Facility REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_USER_PREF_Application_ID ON User_Pref REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_USER_PREF_Concept ON User_Pref REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX PK_user_pref ON User_Pref REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_USER_PRODUCTIVITY_user_name_facility_code ON user_productivity REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX security_id ON User_Security REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX US_NAME ON USER_STATS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX US_WHEN ON USER_STATS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX IX_USERS_TEXT_NAME ON USERS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX UserInstanceId ON USERS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX USERS_NAME ON USERS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX UNC_User_and_Domain_ID ON Users_Domain REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX DUID_Version ON Versions REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:44

ALTER INDEX AccessFlags ON Wfe_GroupsActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX ActivityInstanceID ON Wfe_GroupsActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX ActivityName ON Wfe_GroupsActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX GroupInstanceID ON Wfe_GroupsActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX GroupName ON Wfe_GroupsActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX GroupInstanceID ON Wfe_GroupsUsers REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX GroupName ON Wfe_GroupsUsers REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX Name ON Wfe_GroupsUsers REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX ActivityInstanceID ON Wfe_UsersActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX ActivityName ON Wfe_UsersActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX Name ON Wfe_UsersActivities REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX wf_encounter ON WORK_FLOW REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX wf_facility ON WORK_FLOW REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX ActivityInstanceId ON WQ_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX AgentID ON WQ_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX WD_OBJECT ON WQ_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX WD_TYPE ON WQ_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX WL_OBJECT ON WQ_LINKAGE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX ActivityInstanceId ON WQ_TEMP_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX AgentID ON WQ_TEMP_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX [Type] ON WQ_TEMP_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX WDT_OBJECT ON WQ_TEMP_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX WDT_TYPE ON WQ_TEMP_DEFINITION REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX WLT_OBJECT ON WQ_TEMP_LINKAGE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX WLT_RESULT ON WQ_TEMP_LINKAGE REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

--Biggies (Be Careful, can cause blocking)
ALTER INDEX AS_MRN ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX AS_REFIDTYPE ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX ASSIGN_ENC_FAC ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX assign_user_enc ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_ASSIGNMENTS_CHECKOUTBY_CHECKOUTDATE ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IX_ASSIGNMENTS_LINKED_ID ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX IXC_Assignments_AssignmentID ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 

ALTER INDEX DOC_NAME_Documents ON DOCUMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:46
ALTER INDEX ENCOUNTER_documents ON DOCUMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --10:46
ALTER INDEX MRN_documents ON DOCUMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --04:31
ALTER INDEX UNC_DUID ON DOCUMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --04:39

ALTER INDEX imagedate_PAGES ON Pages REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX PK_PAGES ON Pages REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
ALTER INDEX Version_Page ON Pages REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 