ALTER INDEX action_occurred ON Audit_Trail_2005 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --02:43
ALTER INDEX AUD_ENC ON Audit_Trail_2005 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --02:50
ALTER INDEX AUD_MRN ON Audit_Trail_2005 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --02:39
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2005 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --02:25

ALTER INDEX action_occurred ON Audit_Trail_2006 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:20
ALTER INDEX AUD_ENC ON Audit_Trail_2006 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:50
ALTER INDEX AUD_MRN ON Audit_Trail_2006 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:22
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2006 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --02:40

ALTER INDEX action_occurred ON Audit_Trail_2007 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:51
ALTER INDEX AUD_ENC ON Audit_Trail_2007 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --04:34
ALTER INDEX AUD_MRN ON Audit_Trail_2007 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:51
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2007 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:22

ALTER INDEX action_occurred ON Audit_Trail_2008 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:12
ALTER INDEX AUD_ENC ON Audit_Trail_2008 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:46
ALTER INDEX AUD_MRN ON Audit_Trail_2008 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:40
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2008 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --03:16

ALTER INDEX action_occurred ON Audit_Trail_2011 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --00:21
ALTER INDEX AUD_ENC ON Audit_Trail_2011 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --00:31
ALTER INDEX AUD_MRN ON Audit_Trail_2011 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --00:24
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2011 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --00:19

ALTER INDEX action_occurred ON Audit_Trail_2012 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --04:44
ALTER INDEX AUD_ENC ON Audit_Trail_2012 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:51
ALTER INDEX AUD_MRN ON Audit_Trail_2012 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:19
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2012 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:59

ALTER INDEX action_occurred ON Audit_Trail_2013 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:53
ALTER INDEX AUD_ENC ON Audit_Trail_2013 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --06:48
ALTER INDEX AUD_MRN ON Audit_Trail_2013 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --06:29
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2013 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:04

ALTER INDEX action_occurred ON Audit_Trail_2014 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:31
ALTER INDEX AUD_ENC ON Audit_Trail_2014 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --06:09
ALTER INDEX AUD_MRN ON Audit_Trail_2014 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:26
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2014 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:28

ALTER INDEX action_occurred ON Audit_Trail_2015 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:14
ALTER INDEX AUD_ENC ON Audit_Trail_2015 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --06:19
ALTER INDEX AUD_MRN ON Audit_Trail_2015 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --05:25
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_2015 REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --04:41

ALTER INDEX AUD_ADT_ENC_FAC ON audit_trail_ADT REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX AUD_ADT_MRN_FAC ON audit_trail_ADT REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)
ALTER INDEX AUD_ADT_OCCURRED ON audit_trail_ADT REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX action_occurred ON Audit_Trail_ALL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --07:03
ALTER INDEX AUD_ENC ON Audit_Trail_ALL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --09:52
ALTER INDEX AUD_MRN ON Audit_Trail_ALL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --08:45
ALTER INDEX AUD_USERIDOCCURRED ON Audit_Trail_ALL REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) --06:38

ALTER INDEX EventTime ON Audit_Wfe_Actions_by_UserInstanceID REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX EventExtendedID ON Orig_Wfe_Events REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

ALTER INDEX EventInstanceID ON Orig_Wfe_WorkItemAssignAuditInfo REBUILD WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)