--Rebuild index
--Put Cabinet into simple mode first!!!
ALTER INDEX IX_USER_PRODUCTIVITY_user_name_facility_code ON user_productivity REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_DOCUMENTS ON Documents REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX MRN_documents ON Documents REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON) --00:03:37
ALTER INDEX Version_Page ON Pages REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON) --00:09:51
ALTER INDEX imagedate_PAGES ON Pages REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON) --00:05:34
ALTER INDEX RV_DOCUMENT ON RECORD_VIEWS_DOMAIN REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IX_Composite_Work_Mrn_Fac ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IX_Composite_Work_Enc_Fac ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IX_COMPOSITE_WORK_MRN_ENCOUNTER_FACILITY ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IX_COMPOSITE_WORK_ENCOUNTER_MRN_FACILITY ON composite_work REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX assign_user_enc ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX US_NAME ON USER_STATS REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_PagesCorrected ON PagesCorrected REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON) --00:07:24
ALTER INDEX IDX_sysstats_Name ON SYSSTATS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IDX_sysstats_Name ON SYSSTATS_GLOBAL REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_ServicePayment2110 ON ansi_ServicePayment2110 REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON) --00:01:32
ALTER INDEX AS_MRN ON ASSIGNMENTS REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CDI_DUID ON CAB_DEL_ITEMS REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX follow_up_QUESTATUS ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_TransactionST ON ansi_TransactionST REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX IX_FOLLOW_UP_FOLDER_FACILITY ON FOLLOW_UP REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX docsta_doctype ON DOCUMENT_STATISTICS REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_ARCHIVING_1__17 ON ARCHIVING REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX PK_Outbound_Documents ON Outbound_Documents REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX RV_DESC ON RECORD_VIEWS_DOMAIN REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)

ALTER INDEX ALL ON Pages REBUILD WITH (ONLINE = ON) --Too Long...
ALTER INDEX ALL ON Documents REBUILD WITH (ONLINE = ON) --01:18:46
ALTER INDEX ALL ON Versions REBUILD WITH (ONLINE = ON) --00:08:05

ALTER INDEX ALL ON ASSIGNMENTS REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON ARCHIVING REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON SYSSTATS_GLOBAL REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON FOLLOW_UP REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON MARK_FOR_PURGE_ROLLBACK REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON SIGNATURES REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON DOCUMENT_NAMES REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON composite_work REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON DOCUMENT_STATISTICS REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON CAB_DEL_ITEMS REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON PRODUCTIVITY REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON Facility_File REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON Assigning_Authority REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON Cabinet_Xref REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON WQ_Definition REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON VisualCues REBUILD WITH (ONLINE = ON)

