ALTER INDEX OrderComponentClustIdx ON CV3OrderComponent REBUILD WITH (ONLINE = ON)
ALTER INDEX CV3OrderComponentAI01 ON CV3OrderComponent REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3OrderComponent CV3OrderComponentAI01 WITH FULLSCAN
UPDATE STATISTICS CV3OrderComponent OrderComponentClustIdx WITH FULLSCAN

ALTER INDEX ObsValidValueClustIdx ON CV3ObsValidValue REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3ObsValidValue ObsValidValueClustIdx WITH FULLSCAN

ALTER INDEX VisitIDAlt1Idx ON CV3VisitID REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3VisitID VisitIDAlt1Idx WITH FULLSCAN

ALTER INDEX ChartFlowsheetClustIdx ON CV3ChartFlowsheet REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3ChartFlowsheet ChartFlowsheetClustIdx WITH FULLSCAN

ALTER INDEX CV3ClientVisitLocationPK ON CV3ClientVisitLocation REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3ClientVisitLocation CV3ClientVisitLocationPK WITH FULLSCAN
ALTER INDEX CV3ClientVisitLocationAI02 ON CV3ClientVisitLocation REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3ClientVisitLocation CV3ClientVisitLocationAI02 WITH FULLSCAN

ALTER INDEX CV3MedicationExtensionAI01 ON CV3MedicationExtension REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3MedicationExtension CV3MedicationExtensionAI01 WITH FULLSCAN

ALTER INDEX CV3FRPContractAI01 ON CV3FRPContract REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS CV3FRPContract CV3FRPContractAI01 WITH FULLSCAN

ALTER INDEX SXASNSectionSourcePK ON SXASNSectionSource REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS SXASNSectionSource SXASNSectionSourcePK WITH FULLSCAN
ALTER INDEX SXASNSectionSourceAI01 ON SXASNSectionSource REBUILD WITH (ONLINE = ON)
UPDATE STATISTICS SXASNSectionSource SXASNSectionSourceAI01 WITH FULLSCAN

