ALTER INDEX CV3ClientDocumentCURAI01 ON CV3ClientDocumentCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentCURAI02 ON CV3ClientDocumentCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentCURCI ON CV3ClientDocumentCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentCURPK ON CV3ClientDocumentCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)

ALTER INDEX CV3ClientDocumentARCAI01 ON CV3ClientDocumentARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentARCAI02 ON CV3ClientDocumentARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentARCCI ON CV3ClientDocumentARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocumentARCPK ON CV3ClientDocumentARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)

ALTER INDEX CV3ClientDocHistoryCURAI01 ON CV3ClientDocHistoryCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocHistoryCURCI ON CV3ClientDocHistoryCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocHistoryCURPK ON CV3ClientDocHistoryCUR REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)

ALTER INDEX CV3ClientDocHistoryARCAI01 ON CV3ClientDocHistoryARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocHistoryARCCI ON CV3ClientDocHistoryARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
ALTER INDEX CV3ClientDocHistoryARCPK ON CV3ClientDocHistoryARC REBUILD WITH (SORT_IN_TEMPDB = ON, Statistics_NORECOMPUTE = ON, ONLINE = ON)
